[package]
name = "streamdeck"
description = "Elgato Stream Deck driver and command line interface"
repository = "https://github.com/ryankurte/rust-streamdeck"
version = "0.1.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"
license = "MPL-2.0"


[features]
util = [ "structopt", "simplelog", "humantime" ]
default = [ "util" ]

[dependencies]
hidapi = "1.1.0"
log = "0.4.8"

structopt = { version = "0.3.5", optional = true }
simplelog = { version = "0.7.4", optional = true }
humantime = { version = "1.3.0", optional = true }

[[bin]]
path = "src/main.rs"
name = "streamdeck-cli"
required-features = [ "util" ]
